In [1]:
import pandas as pd
print("pandas funcionando:", pd.__version__)

pandas funcionando: 3.0.5

In [ ]:
# Sprint 1 - Leitura e diagnóstico

In [2]:
'''ler a base'''
import pandas as pd

df = pd.read_csv("Base Varejo.csv", sep=";")
df_original = df.copy()   # cópia para comparar antes/depois
print("Linhas e colunas:", df.shape)
df.head()

Linhas e colunas: (830000, 14)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [3]:
'''colunas e tipos'''
print("Colunas:", list(df.columns))
df.info()

Colunas: ['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

In [4]:
'''valores ausente'''
print(df.isna().sum())
print((df.isna().mean() * 100).round(2))

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64
DATA             0.0
CO_ID            0.0
CL_ID            0.0
CL_GENERO        0.0
CL_EC            0.0
CL_FHL           0.0
CL_SEG           0.0
PR_ID            0.0
PR_CAT           0.0
PR_NOME          0.0
Unnamed: 10    100.0
Unnamed: 11    100.0
Unnamed: 12    100.0
Unnamed: 13    100.0
dtype: float64

In [5]:
'''textos vazios ou só espaços'''
colunas_texto = ["DATA", "CL_GENERO", "CL_SEG", "PR_CAT", "PR_NOME"]
for c in colunas_texto:
    qtd = df[c].astype("string").str.strip().eq("").sum()
    print(c, "->", qtd)

DATA -> 0
CL_GENERO -> 0
CL_SEG -> 0
PR_CAT -> 0
PR_NOME -> 0

In [6]:
'''duplicatas'''
print("Linhas duplicadas:", df.duplicated().sum())
df[df.duplicated(keep=False)].head(10)

Linhas duplicadas: 96553

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
22,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
34,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN

In [7]:
'''inconsistências de texto'''
print(df["PR_CAT"].value_counts(dropna=False))
print("PR_ID com #N/D:", df[df["PR_CAT"] == "#N/D"]["PR_ID"].unique())

PR_CAT
ALIMENTOS     434767
HIGIENE       155574
LIMPEZA       145754
BEBIDAS        43299
PET            32399
ACESSORIOS     14557
#N/D            3650
Name: count, dtype: int64
PR_ID com #N/D: [107]

In [9]:
'''nomes de produto fora do padrão (com letra minúscula)'''
com_minuscula = df[df["PR_NOME"] != df["PR_NOME"].str.upper()]
print("Linhas com PR_NOME fora do padrão:", len(com_minuscula))
print(com_minuscula["PR_NOME"].value_counts())

Linhas com PR_NOME fora do padrão: 7320
PR_NOME
REFRIGERANTE LIMaO    7320
Name: count, dtype: int64

In [8]:
print("Compras diferentes (CO_ID):", df["CO_ID"].nunique())
print("Clientes diferentes (CL_ID):", df["CL_ID"].nunique())

Compras diferentes (CO_ID): 18471
Clientes diferentes (CL_ID): 1000

## Diagnóstico
Cada linha é um **item de uma compra**. A base tem 830.000 linhas,
18.471 compras e 1.000 clientes. Há 4 colunas totalmente vazias,
0 nulos nas demais, 0 textos vazios, 96.553 linhas duplicadas e
3.650 linhas com categoria `#N/D` (produto 107).

Também há uma inconsistência de texto: `REFRIGERANTE LIMaO` (7.320 linhas)
tem uma letra minúscula, enquanto o resto dos nomes está em maiúsculas.

Nada foi alterado ainda. As decisões de limpeza ficam para a Sprint 2.